### ISSUE TITLE
pyTAB not on pip

### ISSUE THREAD

**Issue by sawula** [Thing342/pyTBA#5]
Hi,

`pip install pyTAB`  

gave me the "Could not find the version ... No matching distribution found for pyTAB."  

I also tried all of its camel relatives with no success.

The listing here: `https://pypi.python.org/pypi?%3Aaction=search&term=pytab&submit=search` suggests it's not on pip.  

Please advise.  Thanks in advance.  Excited to use this!
ms

**Comment by wjorda** [comment]
Try `pip install pyTBA`

**Comment by sawula** [comment]
obviously i need more sleep! thanks

**Comment by sawula** [comment]
(moved to new issue)
